# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
install! 'cocoapods', :deterministic_uuids => false

target 'MMTodo_Example-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MMTodo_Example-iOS
  platform :ios, '11.0'
  pod 'MMTodo', :path => '../'

end

target 'MMTodo_Example-macOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MMTodo_Example-macOS
  platform :osx, '10.13'
  pod 'MMTodo', :path => '../'

end
